proyecto_final/core/urls.py
from django.contrib.auth.views import LoginView, LogoutView

from django.urls import path
from . import views

app_name = "core"
urlpatterns = [
    path("", views.index, name = "index"),
    path("about", views.about, name = "about"),
    path('login', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    path('register', views.Register.as_view(), name='register'),
    path('profile', views.Profile.as_view(), name='profile'),
]

proyecto_final/productos/urls.py
from django.urls import path, include
from . import views

app_name = 'productos'

urlpatterns = [
  path("", views.index, name ="index"),

  ##OLD Paths Func views
  #path("product/list", views.product_list, name = "product_list"),
  #path('product/create', views.product_create, name='product_create'),
  #path('product/detail/<int:pk>', views.product_detail, name ='product_detail' ),
  #path('product/update/<int:pk>', views.product_update, name ='product_update' ),
  #path('product/delete/<int:pk>', views.product_delete, name ='product_delete' ),


  ##NEW Paths Class-Based View (CBV)


 # ******* PRODUCTS 
    path(
        'product/list',
        views.ProductList.as_view(),
        name='product_list',
    ),

     path(
        'product/create',
        views.ProductCreate.as_view(),
        name='product_create',
    ),

    path(
        'product/detail/<int:pk>',
        views.ProductDetail.as_view(),
        name='product_detail',
    ),

     path(
        'product/update/<int:pk>',
        views.ProductUpdate.as_view(),
        name='product_update',
    ),

    path(
        'product/delete/<int:pk>',
        views.ProductDelete.as_view(),
        name='product_delete',
    ),


 # ******* Category
  
    path(
        'category/list',
        views.CategoryList.as_view(),
        name = 'category_list'
    ),

    path(
        'category/create',
        views.CategoryCreate.as_view(),
        name='category_create',
    ),

    path(
        'category/detail/<int:pk>',
        views.CategoryDetail.as_view(),
        name='category_detail',
    ),

     path(
        'category/update/<int:pk>',
        views.CategoryUpdate.as_view(),
        name='category_update',
    ),

    path(
        'category/delete/<int:pk>',
        views.CategoryDelete.as_view(),
        name='category_delete',
    ),

 # ******* Brand 
  
    path(
        'brand/list',
        views.BrandList.as_view(),
        name = 'brand_list'
    ),

    path(
        'brand/create',
        views.BrandCreate.as_view(),
        name='brand_create',
    ),

    path(
        'brand/detail/<int:pk>',
        views.BrandDetail.as_view(),
        name='brand_detail',
    ),

    path(
        'brand/update/<int:pk>',
        views.BrandUpdate.as_view(),
        name='brand_update',
    ),

    path(
        'brand/delete/<int:pk>',
        views.BrandDelete.as_view(),
        name='brand_delete',
    ),




]

                      

proyecto_final/proyecto_final/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('products/',include('productos.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto_final/productos/models.py
from django.db import models

class Category(models.Model):
    ''' Groups the products into categories like "Laptops", "Monitors", etc.'''
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self) -> str:
        return self.name
    
    class Meta:
        verbose_name = 'Categoría de Producto'
        verbose_name_plural = 'Categorías de Productos'

class Brand(models.Model):
    '''Represents the brand of the PC equipment'''
    name = models.CharField(max_length = 100)
    description = models.TextField()

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = 'Brand'
        verbose_name_plural = 'Brand'


class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock_quantity = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    specs = models.JSONField(null=True, blank=True)  # To store specifications like RAM, Storage, etc.
    image = models.ImageField(upload_to='core/img/', null=True, blank=True)

    def __str__(self) -> str:
        return f'{self.name} ({self.brand}) ({self.stock_quantity}) ${self.price:.2f}'

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Producto'

    def disminuir_stock(self, cantidad):
        """cantidad es enviado desde el modelo Venta"""
        if self.stock_quantity >= cantidad:
            self.stock_quantity -= cantidad
            self.save()
        else:
            raise ValueError('No hay suficiente stock disponible')

    def aumentar_stock(self, cantidad):
        self.stock_quantity += cantidad
        self.save()

proyecto_final/productos/forms.py
from django import forms
from .models import Product, Category, Brand

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__' 


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__' 


class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = '__all__' 

proyecto_final/productos/views.py
from django.shortcuts import render,redirect

from .forms import ProductForm, CategoryForm ,BrandForm
from .models import Product, Category, Brand

from django.urls import reverse_lazy  ## Class Views
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView ## Class Views


# **** General index

def index(request):
    return render(request,'product/index.html')



# ******* PRODUCTS (Func)

# def product_list(request):
#     # query = Product.objects.all()
#     # context = {'object_list':query}
#     # return render(request,'product/product_list.html', context)
    
#     q = request.GET.get('q')
#     if q:
#         query = Product.objects.filter(name__icontains=q)
#     else:
#         query = Product.objects.all()
#     context = {'object_list': query}
#     return render(request, 'product/product_list.html', context)


# def product_create(request):
#     if request.method == 'GET':
#         form = ProductForm()

#     if request.method == 'POST':
#         form = ProductForm(request.POST)
#         if form.is_valid():
#             # print(form.cleaned_data)
#             form.save()
#             return redirect('productos:product_list')

#     return render(request, 'product/product_form.html', {'form': form})


# def product_detail(request, pk:int):
#     query = Product.objects.get(id = pk)
#     context = {'object':query}
#     return render(request, 'product/product_detail.html',context)


# def product_update(request, pk:int):
#     query = Product.objects.get(id=pk)
#     if request.method == 'GET':
#         form = ProductForm(instance=query)

#     if request.method == 'POST':
#         form = ProductForm(request.POST, instance=query)
#         if form.is_valid():
#             form.save()
#             return redirect('productos:product_list')

#     return render(request, 'product/product_form.html', {'form': form})

# def product_delete(request, pk: int):
#     query = Product.objects.get(id=pk)
#     if request.method == 'POST':
#         query.delete()
#         return redirect('productos:product_list')
#     return render(request, 'product/product_confirm_delete.html', {'object': query})


# ******* PRODUCTS (Class views)


class ProductList(ListView):
    model = Product
    template_name = 'product/product_list.html' ## Preguntar como arreglar
    # context_object_name = 'categorias'
    # queryset = Product.objects.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        q = self.request.GET.get('q')
        if q:
            queryset = Product.objects.filter(name__icontains=q)
        return queryset 
    

class ProductCreate(CreateView):
    model = Product
    from_class = ProductForm
    success_url = reverse_lazy('productos:product_list')
    template_name = 'product/product_form.html' ## Preguntar como arreglar
    fields = '__all__' #['name', 'description', 'price'] 


class ProductDetail(DetailView):
    model = Product
    # context_object_name = 'object'
    template_name = 'product/product_detail.html' ## Preguntar como arreglar


class ProductUpdate(UpdateView):
    model = Product
    from_class = ProductForm
    # context_object_name = 'object'
    template_name = 'product/product_form.html' ## Preguntar como arreglar
    success_url = reverse_lazy('productos:product_list')
    fields = '__all__' #['name', 'description', 'price'] 

class ProductDelete(DeleteView):
    model = Product
    template_name = 'product/product_confirm_delete.html' ## Preguntar como arreglar
    success_url = reverse_lazy('productos:product_list')


# ******* Category (Class views)

class CategoryList(ListView):
    model = Category
    template_name = 'product/category_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        q = self.request.GET.get('q')
        if q:
            queryset = Category.objects.filter(name__icontains=q)
        return queryset 

class CategoryCreate(CreateView):
    model = Category
    from_class = CategoryForm
    success_url = reverse_lazy('productos:category_list')
    template_name = 'product/category_form.html' ## Preguntar como arreglar
    fields = '__all__' #['name', 'description', 'price'] 


class CategoryDetail(DetailView):
    model = Category
    # context_object_name = 'object'
    template_name = 'product/category_detail.html' ## Preguntar como arreglar


class CategoryUpdate(UpdateView):
    model = Category
    from_class = CategoryForm
    # context_object_name = 'object'
    template_name = 'product/category_form.html' ## Preguntar como arreglar
    success_url = reverse_lazy('productos:category_list')
    fields = '__all__' #['name', 'description', 'price'] 

class CategoryDelete(DeleteView):
    model = Category
    template_name = 'product/category_confirm_delete.html' ## Preguntar como arreglar
    success_url = reverse_lazy('productos:category_list')


# ******* Brand (Class views)

class BrandList(ListView):
    model = Brand
    template_name = 'product/brand_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        q = self.request.GET.get('q')
        if q:
            queryset = Brand.objects.filter(name__icontains=q)
        return queryset 

class BrandCreate(CreateView):
    model = Brand
    from_class = BrandForm
    success_url = reverse_lazy('productos:brand_list')
    template_name = 'product/brand_form.html' ## Preguntar como arreglar
    fields = '__all__' #['name', 'description', 'price'] 

class BrandDetail(DetailView):
    model = Brand
    # context_object_name = 'object'
    template_name = 'product/brand_detail.html' ## Preguntar como arreglar


class BrandUpdate(UpdateView):
    model = Brand
    from_class = BrandForm
    # context_object_name = 'object'
    template_name = 'product/brand_form.html' ## Preguntar como arreglar
    success_url = reverse_lazy('productos:brand_list')
    fields = '__all__' #['name', 'description', 'price'] 

class BrandDelete(DeleteView):
    model = Brand
    template_name = 'product/brand_confirm_delete.html' ## Preguntar como arreglar
    success_url = reverse_lazy('productos:brand_list')

proyecto_final/productos/templates/product/brand_confirm_delete.html
{% extends 'core/base.html' %}

{% block header %}
    App Productos: Borrar Marca
{% endblock header %}

{% block main %}
    <p>¿Está seguro que desea borrar la Marca "{{ object.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmo</button>
    </form>
    <button>
        <a href="{% url 'productos:brand_list' %}">Volver</a>
    </button>
{% endblock main %}

proyecto_final/productos/templates/product/brand_create.html
{% extends 'core/base.html' %}

{% block header %}
    Productos: Creación de Marcas
{% endblock header %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Enviar
        </button>
    </form>
    <button>
        <a href="{% url 'productos:index' %}">Volver</a>
    </button>
{% endblock main %}

proyecto_final/productos/templates/product/brand_detail.html
{% extends 'core/base.html' %}

{% load static %}  {# Load static files #}



{% block header %}
    Detalle del Categorias: {{ brand.name }}
{% endblock header %}


{% block main %}
<div class="container my-5">
    <div class="row">
        <div class="col-md-6">
            {% if brand.image %}
                <img src="{{ brand.image.url }}" class="img-fluid rounded" alt="{{ brand.name }}">
            {% else %}
                <img src="{% static 'core/img/no-image.png' %}" class="img-fluid rounded" alt="No Image Available">
              
            {% endif %}
        </div>
        <div class="col-md-6">
            <h2>{{ brand.name }}</h2>
            
            <p><strong>Descripción:</strong> {{ brand.description }}</p>
                 
            <!-- Add additional product details here -->
            <a href="{% url 'productos:brand_update' brand.id %}" class="btn btn-warning">Modificar</a>
            <a href="{% url 'productos:brand_delete' brand.id %}" class="btn btn-danger">Borrar</a>
            <a href="{% url 'productos:brand_list' %}" class="btn btn-secondary">Volver a la lista</a>
        </div>
    </div>
</div>
{% endblock main %}

proyecto_final/productos/templates/product/brand_form.html
{% extends 'core/base.html' %}

{% block header %}
    App Marcas: Formulario de Marcas
{% endblock header %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar</button>
    </form>
    <button>
        <a href="{% url 'productos:index' %}">Volver</a>
    </button>
{% endblock main %}
    

proyecto_final/productos/templates/product/brand_list.html
{% extends 'core/base.html' %}
{% load static %}


{% block header %}
    <div class="container text-center mt-4">
        <h1 class="display-4">Marcas: Lista de Marcas de Productos</h1>
    </div>
{% endblock header %}

{% block main %}
    <div class="container mt-4">
        <form action="{% url 'productos:brand_list' %}" method="get" class="mb-3">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Buscar..." />
                <button type="submit" class="btn btn-primary">Buscar</button>
                <a href="{% url 'productos:brand_create' %}" class="btn btn-success">Crear Registro</a>
            </div>
        </form>

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                    <tr>
                        <td>{{ object.name | upper }}</td>
                        <td>
                            <a href="{% url 'productos:brand_detail' object.id %}" class="btn btn-info btn-sm">Detalle</a>
                            <a href="{% url 'productos:brand_update' object.id %}" class="btn btn-warning btn-sm">Modificar</a>
                            <a href="{% url 'productos:brand_delete' object.id %}" class="btn btn-danger btn-sm">Borrar</a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="2" class="text-center">No hay registros</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock main %}

proyecto_final/productos/templates/product/category_confirm_delete.html
{% extends 'core/base.html' %}

{% block header %}
    App Productos: Borrar Categoría
{% endblock header %}

{% block main %}
    <p>¿Está seguro que desea borrar la categoría "{{ object.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmo</button>
    </form>
    <button>
        <a href="{% url 'productos:category_list' %}">Volver</a>
    </button>
{% endblock main %}

proyecto_final/productos/templates/product/category_create.html
{% extends 'core/base.html' %}

{% block header %}
    Productos: Creación de Categorias
{% endblock header %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Enviar
        </button>
    </form>
    <button>
        <a href="{% url 'productos:index' %}">Volver</a>
    </button>
{% endblock main %}

proyecto_final/productos/templates/product/category_detail.html
{% extends 'core/base.html' %}

{% load static %}  {# Load static files #}

{% block header %}
    Detalle del Categorias: {{ category.name }}
{% endblock header %}


{% block main %}
<div class="container my-5">
    <div class="row">
        <div class="col-md-6">
            {% if category.image %}
                <img src="{{ category.image.url }}" class="img-fluid rounded" alt="{{ category.name }}">
            {% else %}
                <img src="{% static 'core/img/no-image.png' %}" class="img-fluid rounded" alt="No Image Available">
            {% endif %}
        </div>
        <div class="col-md-6">
            <h2>{{ category.name }}</h2>
            
            <p><strong>Descripción:</strong> {{ category.description }}</p>
                 
            <!-- Add additional product details here -->
            <a href="{% url 'productos:category_update' category.id %}" class="btn btn-warning">Modificar</a>
            <a href="{% url 'productos:category_delete' category.id %}" class="btn btn-danger">Borrar</a>
            <a href="{% url 'productos:category_list' %}" class="btn btn-secondary">Volver a la lista</a>
        </div>
    </div>
</div>
{% endblock main %}

proyecto_final/productos/templates/product/category_form.html
{% extends 'core/base.html' %}

{% block header %}
    App Categorias: Formulario de Categorias
{% endblock header %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar</button>
    </form>
    <button>
        <a href="{% url 'productos:index' %}">Volver</a>
    </button>
{% endblock main %}
    

proyecto_final/productos/templates/product/index.html
{% extends 'core/base.html' %}

{% block header %}
    <div class="container text-center mt-4">
        <h1 class="display-4"><strong>Productos</strong></h1>
    </div>
{% endblock header %}

{% block main %}
    <div class="container mt-4">
        <div class="d-flex justify-content-center gap-3">
            <a href="{% url 'productos:product_list' %}" class="btn btn-primary">
                <strong>Lista de Productos</strong>
            </a>
            <a href="{% url 'productos:category_list' %}" class="btn btn-secondary">
                <strong>Lista de Categorías</strong>
            </a>
            <a href="{% url 'productos:brand_list' %}" class="btn btn-success">
                <strong>Lista de Marcas</strong>
            </a>
        </div>
    </div>
{% endblock main %}

proyecto_final/productos/templates/product/product_confirm_delete.html
{% extends 'core/base.html' %}

{% block header %}
    App Productos: Borrar Categoría de Productos
{% endblock header %}

{% block main %}
    <p>¿Está seguro que desea borrar la categoría de productos "{{ object.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmo</button>
    </form>
    <button>
        <a href="{% url 'productos:product_list' %}">Volver</a>
    </button>
{% endblock main %}

proyecto_final/productos/templates/product/product_create.html
{% extends 'core/base.html' %}

{% block header %}
    Productos: Creación de Productos
{% endblock header %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Enviar
        </button>
    </form>
    <button>
        <a href="{% url 'productos:index' %}">Volver</a>
    </button>
{% endblock main %}

proyecto_final/productos/templates/product/product_detail.html
{% extends 'core/base.html' %}

{% load static %}  {# Load static files #}

{% block header %}
    Detalle del Producto: {{ product.name }}
{% endblock header %}

{% block main %}
<div class="container my-5">
    <div class="row">
        <div class="col-md-6">
            {% if product.image %}
                <img src="{{ product.image.url }}" class="img-fluid rounded" alt="{{ product.name }}">
            {% else %}
                <img src="{% static 'img/core/no-image.png' %}" class="img-fluid rounded" alt="No Image Available">
            {% endif %}
        </div>
        <div class="col-md-6">
            <h2>{{ product.name }}</h2>
            <p><strong>Marca:</strong> {{ product.brand }}</p>
            <p><strong>Descripción:</strong> {{ product.description }}</p>
            <p><strong>Precio:</strong> {{ product.price|floatformat:0 }}</p>
     
            <!-- Add additional product details here -->
            <a href="{% url 'productos:product_update' product.id %}" class="btn btn-warning">Modificar</a>
            <a href="{% url 'productos:product_delete' product.id %}" class="btn btn-danger">Borrar</a>
            <a href="{% url 'productos:product_list' %}" class="btn btn-secondary">Volver a la lista</a>
        </div>
    </div>
</div>
{% endblock main %}

proyecto_final/productos/templates/product/product_list.html
{% extends 'core/base.html' %}

{% block header %}
    Productos: Lista de Productos
{% endblock header %}

{% block main %}
    <form action="{% url 'productos:product_list' %}" method="get" class="mb-3">
        <div class="input-group">
            <input type="text" name="q" class="form-control" placeholder="Buscar..." />
            <button type="submit" class="btn btn-primary">Buscar</button>
            <a href="{% url 'productos:product_create' %}" class="btn btn-success">Crear Registro</a>
        </div>
    </form>

    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">Marca</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <td>{{ object.name | upper }}</td>
                    <td>{{ object.brand }}</td>
                    <td>
                        <a href="{% url 'productos:product_detail' object.id %}" class="btn btn-info btn-sm">Detalle</a>
                        <a href="{% url 'productos:product_update' object.id %}" class="btn btn-warning btn-sm">Modificar</a>
                        <a href="{% url 'productos:product_delete' object.id %}" class="btn btn-danger btn-sm">Borrar</a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="3" class="text-center">No hay registros</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock main %}