proyecto_final/core/urls.py
from django.contrib.auth.views import LoginView, LogoutView

from django.urls import path
from . import views

app_name = "core"
urlpatterns = [
    path("", views.index, name = "index"),
    path("about", views.about, name = "about"),
    path('login', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    path('register', views.Register.as_view(), name='register'),
    path('profile', views.Profile.as_view(), name='profile'),
]

proyecto_final/productos/urls.py
from django.urls import path, include
from . import views

app_name = 'productos'

urlpatterns = [
  path("", views.index, name ="index"),

  ##OLD Paths Func views
  #path("product/list", views.product_list, name = "product_list"),
  #path('product/create', views.product_create, name='product_create'),
  #path('product/detail/<int:pk>', views.product_detail, name ='product_detail' ),
  #path('product/update/<int:pk>', views.product_update, name ='product_update' ),
  #path('product/delete/<int:pk>', views.product_delete, name ='product_delete' ),


  ##NEW Paths Class-Based View (CBV)


 # ******* PRODUCTS 
    path(
        'product/list',
        views.ProductList.as_view(),
        name='product_list',
    ),

     path(
        'product/create',
        views.ProductCreate.as_view(),
        name='product_create',
    ),

    path(
        'product/detail/<int:pk>',
        views.ProductDetail.as_view(),
        name='product_detail',
    ),

     path(
        'product/update/<int:pk>',
        views.ProductUpdate.as_view(),
        name='product_update',
    ),

    path(
        'product/delete/<int:pk>',
        views.ProductDelete.as_view(),
        name='product_delete',
    ),


 # ******* Category
  
    path(
        'category/list',
        views.CategoryList.as_view(),
        name = 'category_list'
    ),

    path(
        'category/create',
        views.CategoryCreate.as_view(),
        name='category_create',
    ),

    path(
        'category/detail/<int:pk>',
        views.CategoryDetail.as_view(),
        name='category_detail',
    ),

     path(
        'category/update/<int:pk>',
        views.CategoryUpdate.as_view(),
        name='category_update',
    ),

    path(
        'category/delete/<int:pk>',
        views.CategoryDelete.as_view(),
        name='category_delete',
    ),

 # ******* Brand 
  
    path(
        'brand/list',
        views.BrandList.as_view(),
        name = 'brand_list'
    ),

    path(
        'brand/create',
        views.BrandCreate.as_view(),
        name='brand_create',
    ),

    path(
        'brand/detail/<int:pk>',
        views.BrandDetail.as_view(),
        name='brand_detail',
    ),

    path(
        'brand/update/<int:pk>',
        views.BrandUpdate.as_view(),
        name='brand_update',
    ),

    path(
        'brand/delete/<int:pk>',
        views.BrandDelete.as_view(),
        name='brand_delete',
    ),




]

                      

proyecto_final/proyecto_final/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('products/',include('productos.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto_final/core/models.py
from django.db import models

# Create your models here.

proyecto_final/core/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


       
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

proyecto_final/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User

from django.shortcuts import render

from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from .forms import CustomUserCreationForm, UserProfileForm


def index(request):
    return render(request, 'core/index.html')

def about(request):
    return render(request, 'core/about.html')

class Register(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'core/register.html'
    success_url = reverse_lazy('core:login')

class Profile(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'core/profile.html'
    success_url = reverse_lazy('core:index')

    def get_object(self):
        # Devuelve el usuario actual, si no, Django va a esperar un pk en la URL
        return self.request.user

proyecto_final/core/templates/core/about.html
{% extends 'core/base.html' %}
{% load static %}

{% block header %}
    Discover more about me and the company.
{% endblock header %}

{% block main %}
<!-- About Me Section -->
<section class="py-5 bg-light" id="scroll-target">
    <div class="container px-5 my-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6">
                <img class="img-fluid rounded mb-5 mb-lg-0" src="{% static 'core/img/alvaro.jpeg' %}" alt="About Me" />
            </div>
            <div class="col-lg-6">
                <h2 class="fw-bolder">About Me</h2>
                <p class="lead fw-normal text-muted mb-0">
                    Profesional con más de 8 años de experiencia en operaciones de negocio en entornos de startups. 
                    Experto en crecimiento y eficiencia operativa, liderando estrategias que optimizan el rendimiento. 
                    Posee un título en Administración de Empresas y un posgrado en Finanzas. 
                    Experiencia en roles clave en empresas reconocidas como Beat App, Rappi y actualmente en NinjaOne como Data Specialist.
                </p>
                
                <!-- LinkedIn Button -->
                <a href="https://www.linkedin.com/in/alvarocancino/" class="btn btn-primary mt-3" target="_blank">
                    <i class="fab fa-linkedin"></i> <strong>LinkedIn</strong>
                </a>
                <!-- Github Button -->
                <a href="https://github.com/alvaro3dd" class="btn btn-dark mt-3" target="_blank">
                    <i class="fab fa-github"></i> <strong>Github</strong>
                </a>
            </div>
        </div>
    </div>
</section>

<!-- About the Company Section -->
<section class="py-5 bg-light" id="scroll-target">
    <div class="container px-5 my-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6">
                <img class="img-fluid rounded mb-5 mb-lg-0" src="{% static 'core/img/business.jpg' %}" alt="About Company" />
            </div>
            <div class="col-lg-6">
                <h2 class="fw-bolder">About the Company</h2>
                <p class="lead fw-normal text-muted mb-0">
                    BucaTech es una página web especializada en la venta de componentes de computación, diseñada para satisfacer las necesidades de entusiastas de la tecnología, gamers y profesionales del sector. 
                    
                    <br><br>
                    BucaTech se posiciona como una opción confiable para quienes buscan componentes de computación de alta calidad, con un enfoque en la satisfacción del cliente y una experiencia de compra fluida. 
                    Su compromiso con la tecnología y la innovación la convierte en una elección destacada en el mercado de la computación.
                </p>
            </div>
        </div>
    </div>
</section>
{% endblock main %}

proyecto_final/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>BucaTech</title>
        <!-- Favicon-->
        <link rel="icon"
              type="image/x-icon"
              href="{% static 'core/assets/favicon.ico' %}  " />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
              rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
        <!-- links para trabajar sin el tema -->
        <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
       rel="stylesheet"
       integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
       crossorigin="anonymous" /> -->
        <!-- <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script> -->
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            {% include 'core/componentes/navbar.html' %}
            
           
            <!-- Blog preview section-->
            <section class="py-3">
                <div class="container px-5 my-1">
                    <div class="row gx-5 justify-content-center">
                        <div class="col-lg-8 col-xl-6">
                            <div class="text-center">
                            
                                <h2 class="fw-bolder">{% block header %}
                                    
                                    {% endblock header %}</h2>
                                
                            </div>
                        </div>
                    </div>
                    
                </div>
            </section>
            <section class="py-3">
                <div class="container px-5 my-1">
                    <div class="row gx-5 justify-content-center">
                        {% block main %}
                        {% endblock main %}
                
                    </div>
                    
                </div>
            <section>
        </main>
      

        <!-- Footer-->
        {% include 'core/componentes/footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src=" {% static 'core/js/scripts.js' %} "></script>
    </body>
</html>

proyecto_final/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block header %}
{% endblock header %}


{% block main %}
 <!-- Header-->
 <header class="bg-dark py-5">
    <div class="container px-5">
        <div class="row gx-5 align-items-center justify-content-center">
            <div class="col-lg-8 col-xl-7 col-xxl-6">
                <div class="my-5 text-center text-xl-start">
                    <h1 class="display-5 fw-bolder text-white mb-2">BucaTech</h1>
                    <p class="lead fw-normal text-white-50 mb-4">BucaTech es una página web especializada en la venta de componentes de computación, diseñada para satisfacer las necesidades de entusiastas de la tecnología, gamers y profesionales del sector.</p>
                    <p class="lead fw-normal text-white-50 mb-4">*Para ingresar a ver el portafolio de productos por favor realicé su log-in o registro en la plataforma:</p>
                    <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                        <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'core:login' %}">Get Started</a>
                        <a class="btn btn-outline-light btn-lg px-4" href="{% url 'core:about' %}">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center"><img class="img-fluid rounded-3 my-5" src="{% static 'core/img/logo3.png' %}" alt="..." /></div>
        </div>
    </div>
</header>


<!-- Testimonial section-->
<div class="py-5 bg-light">
    <div class="container px-5 my-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-10 col-xl-7">
                <div class="text-center">
                    <div class="fs-4 mb-4 fst-italic">"BucaTech ha sido el mejor sitio web para adquirir equipos de computación. 
                        El año pasado compré una tarjeta de video y una laptop, las cuales me han funcionado muy bien. 
                        La calidad de los productos es excepcional y el servicio al cliente es insuperable. Definitivamente, volveré a comprar aquí para mis futuras necesidades tecnológicas. ¡Altamente recomendados!"</div>
                    <div class="d-flex align-items-center justify-content-center">
                        <img class="rounded-circle me-3" src="{% static 'core/img/review1.jpg' %}" alt="..." style="width: 40px; height: 40px;" />
                        <div class="fw-bold">
                            Andres Martinez
                            <span class="fw-bold text-primary mx-1">/</span>
                            IT Tech, Pomodoro
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row gx-5">
    <!-- Card 1 -->
    <div class="col-lg-4 mb-5">
        <div class="card h-100 shadow border-0">
            <img class="card-img-top" src="{% static 'core/img/tv1.png' %}" alt="..." />
            <div class="card-body p-4">
                <div class="badge bg-primary bg-gradient rounded-pill mb-2">10% off</div>
                <a class="text-decoration-none link-dark stretched-link" href="{% url 'productos:index' %}">
                    <h5 class="card-title mb-3">Tarjetas de Video</h5>
                </a>
                <p class="card-text mb-0">Descubre el poder gráfico con nuestras tarjetas de video. Diseñadas para ofrecer un rendimiento excepcional,
                     optimizan tus juegos y aplicaciones con imágenes nítidas y fluidas. ¡Lleva tu experiencia visual al siguiente nivel!</p>
            </div>
            <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                <div class="d-flex align-items-end justify-content-between">
                    <div class="d-flex align-items-center">
                        <div class="small"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Card 2 -->
    <div class="col-lg-4 mb-5">
        <div class="card h-100 shadow border-0">
            <img class="card-img-top" src="{% static 'core/img/tv2.png' %}" alt="..." />
            <div class="card-body p-4">
                <div class="badge bg-primary bg-gradient rounded-pill mb-2">25% off</div>
                <a class="text-decoration-none link-dark stretched-link" href="#!">
                    <h5 class="card-title mb-3">Tarjetas de Video</h5>
                </a>
                <p class="card-text mb-0">Transforma tu espacio de trabajo y juego con nuestras pantallas de PC de alta definición. 
                    Disfruta de colores vibrantes y una claridad asombrosa que elevan tu experiencia visual.
                     ¡Explora nuestra selección y mejora tu productividad y entretenimiento hoy mismo!</p>
            </div>
            <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                <div class="d-flex align-items-end justify-content-between">
                    <div class="d-flex align-items-center">
                        <div class="small"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Card 3 -->
    <div class="col-lg-4 mb-5">
        <div class="card h-100 shadow border-0">
            <img class="card-img-top" src="{% static 'core/img/tv3.png' %}" alt="..." />
            <div class="card-body p-4">
                <div class="badge bg-primary bg-gradient rounded-pill mb-2">10% off</div>
                <a class="text-decoration-none link-dark stretched-link" href="#!">
                    <h5 class="card-title mb-3">Tarjetas de Video</h5>
                </a>
                <p class="card-text mb-0">Optimiza tu experiencia de uso con nuestros periféricos de última generación. 
                    Desde teclados y ratones hasta auriculares, cada producto 
                    está diseñado para ofrecerte comodidad y rendimiento excepcionales. ¡Descubre nuestra variedad y lleva tu configuración al siguiente nivel!</p>
            </div>
            <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                <div class="d-flex align-items-end justify-content-between">
                    <div class="d-flex align-items-center">
                        <div class="small"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




<!-- Call to action-->
<aside class="bg-primary bg-gradient rounded-3 p-4 p-sm-5 mt-5">
    <div class="d-flex align-items-center justify-content-between flex-column flex-xl-row text-center text-xl-start">
        <div class="mb-4 mb-xl-0">
            <div class="fs-3 fw-bold text-white">New products, delivered to you.</div>
            <div class="text-white-50">Sign up for our newsletter for the latest updates.</div>
        </div>
        <div class="ms-xl-4">
            <div class="input-group mb-2">
                <input class="form-control" type="text" placeholder="Email address..." aria-label="Email address..." aria-describedby="button-newsletter" />
                <button class="btn btn-outline-light" id="button-newsletter" type="button">Sign up</button>
            </div>
            <div class="small text-white-50">We care about privacy, and will never share your data.</div>
        </div>
    </div>
</aside>

{% endblock main %}

proyecto_final/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block header %}
    Login
{% endblock header %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Iniciar sesión</button>
    </form>
    <p>
        ¿No tienes una cuenta? <a href="{% url 'core:register' %}">Regístrate aquí</a>
    </p>
{% endblock main %}

proyecto_final/core/templates/core/logout.html
{% extends 'core/base.html' %}

{% block header %}
    Logout
{% endblock header %}

{% block main %}
    <div style="text-align: center;">
        <p>Has cerrado sesión</p>
    </div>
{% endblock main %}

proyecto_final/core/templates/core/profile.html
{% extends 'core/base.html' %}

{% block header %}
    Actualizar Perfil del Usuario
{% endblock header %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar cambios</button>
    </form>
{% endblock main %}

proyecto_final/core/templates/core/register.html
{% extends 'core/base.html' %}

{% block header %}
    Registro de Usuario
{% endblock header %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Registrarse</button>
    </form>
{% endblock main %}