proyecto_final/core/urls.py
from django.contrib.auth.views import LoginView, LogoutView

from django.urls import path
from . import views

app_name = "core"
urlpatterns = [
    path("", views.index, name = "index"),
    path("about", views.about, name = "about"),
    path('login', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    path('register', views.Register.as_view(), name='register'),
    path('profile', views.Profile.as_view(), name='profile'),
]

proyecto_final/productos/urls.py
from django.urls import path, include
from . import views

app_name = 'productos'

urlpatterns = [
  path("", views.index, name ="index"),

  ##OLD Paths Func views
  #path("product/list", views.product_list, name = "product_list"),
  #path('product/create', views.product_create, name='product_create'),
  #path('product/detail/<int:pk>', views.product_detail, name ='product_detail' ),
  #path('product/update/<int:pk>', views.product_update, name ='product_update' ),
  #path('product/delete/<int:pk>', views.product_delete, name ='product_delete' ),


  ##NEW Paths Class-Based View (CBV)


 # ******* PRODUCTS 
    path(
        'product/list',
        views.ProductList.as_view(),
        name='product_list',
    ),

     path(
        'product/create',
        views.ProductCreate.as_view(),
        name='product_create',
    ),

    path(
        'product/detail/<int:pk>',
        views.ProductDetail.as_view(),
        name='product_detail',
    ),

     path(
        'product/update/<int:pk>',
        views.ProductUpdate.as_view(),
        name='product_update',
    ),

    path(
        'product/delete/<int:pk>',
        views.ProductDelete.as_view(),
        name='product_delete',
    ),


 # ******* Category
  
    path(
        'category/list',
        views.CategoryList.as_view(),
        name = 'category_list'
    ),

    path(
        'category/create',
        views.CategoryCreate.as_view(),
        name='category_create',
    ),

    path(
        'category/detail/<int:pk>',
        views.CategoryDetail.as_view(),
        name='category_detail',
    ),

     path(
        'category/update/<int:pk>',
        views.CategoryUpdate.as_view(),
        name='category_update',
    ),

    path(
        'category/delete/<int:pk>',
        views.CategoryDelete.as_view(),
        name='category_delete',
    ),

 # ******* Brand 
  
    path(
        'brand/list',
        views.BrandList.as_view(),
        name = 'brand_list'
    ),

    path(
        'brand/create',
        views.BrandCreate.as_view(),
        name='brand_create',
    ),

    path(
        'brand/detail/<int:pk>',
        views.BrandDetail.as_view(),
        name='brand_detail',
    ),

    path(
        'brand/update/<int:pk>',
        views.BrandUpdate.as_view(),
        name='brand_update',
    ),

    path(
        'brand/delete/<int:pk>',
        views.BrandDelete.as_view(),
        name='brand_delete',
    ),




]

                      

proyecto_final/proyecto_final/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('products/',include('productos.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto_final/core/models.py
from django.db import models

# Create your models here.

proyecto_final/core/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


       
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

proyecto_final/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User

from django.shortcuts import render

from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from .forms import CustomUserCreationForm, UserProfileForm


def index(request):
    return render(request, 'core/index.html')

def about(request):
    return render(request, 'core/about.html')

class Register(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'core/register.html'
    success_url = reverse_lazy('core:login')

class Profile(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'core/profile.html'
    success_url = reverse_lazy('core:index')

    def get_object(self):
        # Devuelve el usuario actual, si no, Django va a esperar un pk en la URL
        return self.request.user

proyecto_final/core/templates/core/componentes/card.html
<div class="col mb-5 h-100">
    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3">
        <i class="bi bi-collection"></i>
    </div>
    <h2 class="h5">{{ titulo }}</h2>
    <p class="mb-0">
        {{ texto }}
    </p>
</div>

proyecto_final/core/templates/core/componentes/footer.html
<footer class="bg-dark py-2 fixed-bottom">
    <div class="container px-4 px-lg-5">
        <div class="col-auto">
            <div class="small m-0 text-white text-center">Copyright &copy; Hecho en Coderhouse por AJCR</div></div>
            </div>
        </div>
    </div>
</footer>

proyecto_final/core/templates/core/componentes/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'core:index' %}">
            <strong>BucaTech</strong>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" href="{% url 'core:index' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'core:about' %}">About</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'productos:index' %}">Productos</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'core:profile' %}">{{ user.username }}</a></li>
                {% if user.vendedor.avatar %}
                <img src="{{ user.vendedor.avatar.url }}" alt="avatar" style="height: 30px" />
                {% else %}
                <img src="{% static 'core/img/perfil.png' %}" alt="avatar" style="height: 30px" />
                {% endif %}
            <form action="{% url 'core:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Logout</button>
            </form>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'core:login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
</div>
</nav>